<a href="https://colab.research.google.com/github/Suyashh-hub/Python-assignments/blob/main/Pyhton_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#one dimentional array
import numpy as np
list1=[11,22,33,44,55,66]
array1=np.array(list1)
print(list1)
print(array1)

[11, 22, 33, 44, 55, 66]
[11 22 33 44 55 66]


In [ ]:
#two dimentional array
import numpy as np
list1=[[11,22,33],[44,55,66]]
array1=np.array(list1)
print(array1)

[[11 22 33]
 [44 55 66]]


In [ ]:
#three dimentional array
import numpy as np
list1=[[11,22,33],[44,55,66],[77,88,99]]
array1=np.array(list1)
print(array1.shape)
print(array1.ndim)
print(array1.size)
print(array1.dtype)
print(array1.itemsize )

(3, 3)
2
9
int64
8


In [ ]:
#use of range
import numpy as np
array1=np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [ ]:
#reshape use
import numpy as np
array1=np.arange(11,17).reshape(3,2)
print(array1)

[[11 12]
 [13 14]
 [15 16]]


In [ ]:
#zeroes create matrix
import numpy as np
array1=np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [ ]:
import numpy as np
array1 =np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-3:-1])
print(array1[::2])

[20 30]
[20 40 60]
[70 60]
[10 30 50 70]


In [ ]:
import numpy as np
array1 =np.array([[15,16,17],[25,26,27],[35,36,37],[45,46,47]])
print(array1[1,])
print(array1[:,1])
print(array1[1:3,1:3])
print(array1[1:3,])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])
print(array1[2:, 1])
print(array1[0, 1:3])

[25 26 27]
[16 26 36 46]
[[26 27]
 [36 37]]
[[25 26 27]
 [35 36 37]]
[[16 17]
 [26 27]
 [36 37]
 [46 47]]
[26 36]
[[25]
 [35]]
[36 46]
[16 17]


In [ ]:
#Matrix multipliocstion
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x@y
print(z)

[[37 40]
 [85 92]]


In [ ]:
#Matrix multipliocstion
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x/y
print(z)

[[0.09090909 0.16666667]
 [0.23076923 0.28571429]]


In [ ]:
#Matrix multipliocstion
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x+y
print(z)

[[12 14]
 [16 18]]


In [ ]:
#Matrix multipliocstion
import numpy as np
x=np.array([[1,2],[3,4]])
y=np.array([[11,12],[13,14]])
z=x-y
print(z)

[[-10 -10]
 [-10 -10]]


In [ ]:
import numpy as np
lst=[]
n=int(input("Enter number of elements: "))
for i in range(n):
  element=int(input(f"Enter element {i+1}: "))
  lst.append(element)
print("List: ",lst)


In [ ]:
s1="SBJAIN college 54678"

count=0
count1=0
count2=0
for i in s1:
  if i.isspace():
    count+=1
  if i.isdigit():
    count1+=1
  if i.isalpha():
    count2+=1
print(count)
print(count1)
print(count2)

In [ ]:
#index and find
s="welcome to python programming"
print(s.find("p"))#find first index  position of p ie: 11
print(s.index("p"))#also same
print(s.find("p",12))#find p from 12 index to end
print(s.index("p",12))#same like find
print(s.find("p",1,13))#find p from 1 to 12 index
print(s.index("p",1,13))#same like find
#difference in both
print(s.find("k"))  #give -1
#print(s.index("k")) #give error value error
#note find function only available with string
# not available in tupple,list,set but index function available

In [ ]:
s="welcome to all python programming "
print(s.split()) #by default split from space and return answer in list
print(s.split("p"))#jaha jaha p waha , ayega
#partition
#print(s.partition())#here must give value for partion nahi tao error
print(s.partition("p"))
#p ke pahele ek part,then  p,then baki part give answer in tupple
#output=>('welcome to all ', 'p', 'ython programming ')
#jony jony wal aexample

In [ ]:
#strip,rstrip,ltsrip
s=" sbjain"
print(s)# its print as it is
print(s.lstrip())#remove left space
#rstrip
s="sbjain     "
print(s)
print(s.rstrip())#its remove but nor see
#to see rstrip
s="sbjain     "
print(len(s))#its count all
print(len(s.rstrip()))#after remove ight space
#strip remove both side space

In [ ]:
#list demo empty list print
my_list1 = [11,22,33]
print(my_list1)
my_list2=list([])
print(my_list2)

In [ ]:
#list to print
my_list1=[1,"hindi",33,44,"edurekha"]
my_list2=list([454,"yogesh","sanjay",55,66,77])
print(my_list1)
print(my_list2)

In [ ]:
#print list using slice
my_list1=[1,"hindi",33,44,"edurekha"]
print(my_list1[:])
print(my_list1[0:3])
print(my_list1[::-1])
print(my_list1[0:5:2])
print(my_list1[1][2])
print(my_list1[-1][1])

In [ ]:
my_list1=[1,"hindi",33,44,"edurekha"]
my_list2=[11,22,33]
my_list1.append([555,22] )    #USE OF APPEND FUNCTION
print(my_list1)
print(len(my_list1))
my_list1.extend([444,666])    #USE OF EXTEND FUN
print(my_list1)
print(len(my_list1))
my_list1.insert(1,"sanjay")    #USE OF INSERT FUNCTION
print(my_list1)
print(len(my_list1))
my_list2.insert(1,99)
print(my_list2)
print(my_list1 + [ "katre"])   #add content to given list but original list not effect
print(my_list1)
print(my_list1 *2)   #list is multiply by 2 shows list 2 times
print(my_list1)


In [ ]:
# index ,count in list
my_list1=[1, 'sanjay', 'hindi', 33, 44, 'edurekha']
print(my_list1.index("edurekha"))  #find index no. of element
print(my_list1.count("edurekha"))   #find how many times particular element in a given list
new = [11, 45, 22, 1, 3]
print(sorted(new))  # sorted new list element and print but original not change
print(new)             # ORIGINAL PRINT AS IT Is
new.sort(reverse=True)  #short original list in decending order if rev=true else accending order
print(new)
new.reverse()
print(new)

In [ ]:
t=tuple("Hello")
print(t)

In [ ]:
l=['a','e','i','o','u']
t=tuple(l)
print(t)

In [ ]:
t=tuple(input("Enter elements: "))
print(t)

In [ ]:
#create empty tupple
t=()
print(t)
t=tuple()
print(t)


In [ ]:
#create
t=(1)
print(type(t))
t=(1,)
print(type(t))

In [ ]:
#create different tuple
t=(1,2,3,4)
print(t)
t=(1.2,1.2,1.4,"a")
print(t)

In [ ]:
#take input from user
t1=tuple(input("Enter Element:"))
print(t1)

In [ ]:
#crete tuple using tuple function
t=tuple("HELLO")
print(t)
l=[1,2,3,4,5]
t=tuple(l)
print(t)

In [ ]:
#nested tuple
t=(1,2,3,(44,55))
print("NESTED TUPPLE=>",t)

In [ ]:
#crete tuple using tuple function
t=tuple("HELLO")
print(t)
l=[1,2,3,4,5]
t=tuple(l)
print(t)

In [ ]:

#class tuple when , insert
s="PYTHON"
print(type(s))
s=("PYTHON",)
print(type(s))

In [ ]:
#convert into tupple
l=[1,2,3]
print(tuple(l))
s="python"
print(tuple(s))
#conver dic to tuple
d={1:"a",2:"b",3:"c"}
print(tuple(d))  #by default key
print(tuple(d.values())) #here value take not keys

In [ ]:
#packed and unpacked
t=1,2   #packed
print(t)
x,y=(1,2)  #unpacked
print(x,y)

In [ ]:
#traversal
#user input and for loop tuple creation
t=tuple()
totalvalue=int(input("How many element u enter in tupple:"))
for i in range(totalvalue):
    val=int(input("Enter element:"))
    t=t+(val,)
print(t)

In [ ]:
#traversing tuple using for loop
t=(11,22,33,44,55,66)
for i in t:
    print(i,end=" ")

In [ ]:
t=(11,22,33,44,55,66)
for i in range(len(t)):
    print(t[i],end=" ")

In [ ]:
#we can change index value
t=(11,22,33,44,55,66,77)
print(t[0])  #11
print(t[-1])  #77
print(t[-4])   #44
#not change in tuple
t[0]=0    #give error
print(t)

In [ ]:
#slicing
t=(99,88,77,66,55,44,33,22)
print(t[0:5])  #0 to 3
print(t[::-1])  #reverse
print(t[-1:-5:-1])  #22,33,44,55  start :end-1:step


In [ ]:
#concatenete,replicate,membership
t=(11,22,33)
print(t)
print(id(t))
t=t*3
print(t)
print(id(t))

In [ ]:
#2. Concatenate the tuples (1, 2, 3) and (4, 5, 6) and store the result in a new tuple.
t1=(1,2,3)
t2=(4,5,6)
t3=t1+t2
print(t3)

In [ ]:
t=(10,12,14,20,22,24,30,32,34)
seq=t[3:-3]
print(seq)
seq1=t[2:-2]
print(seq1)

In [ ]:
my_tuple = (10, "hello", 3.14)

# You can print the tuple to see its contents:
# print(my_tuple)
# (10, 'hello', 3.14)


In [ ]:
my_tuple = (1, 2, 3, 4, 5)
third_element = my_tuple[2]
print(third_element)


In [ ]:
t1=(1,2,3)
t2=(4,5,6)
t3=t1+t2
print(t3)

In [ ]:
# Define the tuple
my_tuple = (1, 2, 3)

# Unpack the tuple
v1, v2, v3 = my_tuple

# Print the values
print(v1) # Output: 1
print(v2) # Output: 2
print(v3) # Output: 3


In [ ]:
#create dictionary
dic={ }  #empty dictionary
print(dic)
print(type(dic))
d=dict()
print(d)
print(type(d))
d={1:"x",2:"y",3:"z"}
print(d)
print(d.keys())
print(d.values())
print(d.items())


In [ ]:
#four ways to create dictionary
d1= {"a":"apple","b":"orange","c":"mango"}
d2=dict(a="apple",b="orange",c="mango")
d3=dict([("a","apple"),("b","orange"),("c","mango")])
d4=dict({"a":"apple","b":"orange","c":"mango"})
print(d1==d2==d3==d4)

In [ ]:
#check equality
d1={1:99,2:67,3:55}
d2={1:99,2:67,3:55}
print(d1==d2)

d={1:"xx",2:"yy",3:"uu"}
print(d[1])#1 indicate key

In [ ]:
#create empty dictionary and add item
d1=dict()
d1[1]="one"
d1[2]="two"
d1[3]="three"
d1[4]="four"
print(d1)

In [ ]:
def sum():
    a=int(input("Enter value of a:"))
    b = int(input("Enter value of b:"))
    print(a+b)

sum()     #funtion call


In [ ]:

#passing parameters
def sum(m,n):  #formal arguments
    print(m+n)

a=int(input("Enter value of a:"))
b = int(input("Enter value of b:"))
sum(a,b)     #funtion call passing parameter actual arguments


In [ ]:
#function call without argument without return
def evenodd():
    num=int(input("Enter a number:"))
    if num%2==0:
        print(num,"even number")
    else:
        print(num, "odd number")

evenodd()

In [ ]:
#function call with argument pass  without return
def evenodd(n):
    if  n% 2 == 0:
        print(n, "even number")
    else:
        print(n, "odd number")

num = int(input("Enter a number:"))
evenodd(num)  #pass argument

In [ ]:
#functio call with argument pass without return
def add(a,b):
       sum=a+b
       print("sum of two number:",sum)
n1=int(input("Enter  number:"))
n2 = int(input("Enter  number:"))
add(n1,n2)

In [ ]:
#function call with argument pass with return
def add(a,b):

    sum=a+b
    return  sum

n1=int(input("Enter  number:"))
n2 = int(input("Enter  number:"))
result=add(n1,n2)  #pass  argument
print("sum of two number:",result)

In [ ]:
#multiple value return
def example():
    return 11,22,33
print(example())

def example():
    return 11,22,33,44

t=example()
print(t)
a,b,c,d=example() #here also packed so unpacked
print(a,b,c,d,sep=" ")

In [ ]:
#example
def sum(A,B,C=10,D=90):
    print(A+B+C+D)
A=10
B=20
C=30
D=40
sum(1,2,3,4)


In [ ]:
#cross value assign to particular  variable
def result(eng,maths,hindi=11,chem=00):
        print(eng)
        print(maths)

result(maths=50,eng=90)

In [ ]:
def Student(name,marks=33):
  print(name)
  print(marks)
Student('suyash',50)

In [ ]:
def ADD(Sci,Maths,Eng=90,Hindi=9):
  print(Sci+Maths+Eng+Hindi)
ADD(Maths=99,Sci=98)

In [ ]:
#global keywords
def simple():
    global a  #so a is global variable
    a=99
a=100
print("after call b=",a)
simple()
print("after call a=",a)


In [ ]:

def simple():
    a=100
    b+=10  #we cant change b because its global
b=90
simple()

In [ ]:
#Nested loop
def outer():
      a=10
      print("outer:",a)
      def inner():
          print("I am inner loop")
      inner()

outer()

In [ ]:
#object
class Computer:
    pass

a=10
print(type(a))
c1=Computer()
print(type(c1))

In [ ]:
class Cal:
    def get(self):
        self.n1=int(input("Enter Number:"))
        self.n2 = int(input("Enter Number:"))
    def display(self):
        self.sum=self.n1+self.n2
        print(self.sum)

c1=Cal()
c1.get()   #call methode with self object
c1.display()

In [ ]:
#CRETE ROWS INDEX AND COLUMN NAME IN DATAFRAME BY USER
import pandas  as pd
a1=[1,2,3,88]    #we create three list of array data and create datraframe then
a2=[7,0,9,8]
a3=[1,5,4,7]
list=[a1,a2,a3]
s=pd.DataFrame(list,index=["R1","R2","R3"],columns=["C1","C2","C3","C4"])   #we create column also in dataframe
print(s)

In [ ]:
#CREATE ONE DATA FRAME USE LIST
import pandas  as pd
list=[1,2,3,4]
s=pd.DataFrame(list)
print(s)

In [ ]:
#dictionary of lists example
#NOW WE CREATE DATAFRAME USING DICTIONARY
import pandas as pd
a1=["11A","12B","11C","12D"]
a2=["sanju","umesh","raju","viju"]
a3=[90,80,70,66]
dict={"Class":a1,"Name":a2,"Marks":a3}   #keys become column in dictionary
s=pd.DataFrame(dict)
print(s)

In [ ]:
#LIST OF DICTIONARIES,,dictionary banaaya fir ek list mai dala that is list of dictionariesssss

#all values given if some values miss its shows Nan we show below example
import pandas as pd
Class12A={"Name":"Raja","Class":"12A","Marks":"90"}
Class12B={"Name":"Sanju","Class":"12B","Marks":"80"}
Class12C={"Name":"Viju","Class":"12C","Marks":"99"}
list=[Class12A,Class12B,Class12C]
s=pd.DataFrame(list,index=["R1","R2","R3"])
print(s)

In [ ]:
#create dataframe by dictionary of series
#1)
import pandas as pd
s1=pd.Series(["Raju","Sonu","Suny"])
s2=pd.Series(["12A","12B","12C"])
s3=pd.Series([90,99,88])
dict={"Name":s1,"Class":s2,"Marks":s3}
data=pd.DataFrame(dict)
print(data)


In [ ]:
#last DICTIONARY OF DICTIONARY ITS MAIN
import pandas as pd
dict={"Marketing":{"Name":"sanjay","Age":"30","Grade":"1"},"Sales":{"Name":"yogesh","Age":"40","Grade":"2"},
      "Sports":{"Name":"umesh","Age":"45","Grade":"3"}}  #make here dictionary of dictionariessss
#point note outer keys become column and inner keys become rows please remember this point
s=pd.DataFrame(dict)
print(s)

In [ ]:
import pandas as pd
df=pd.read_excel("/content/student.xlsx")
print(df)

In [ ]:
#DATA FRAME ATTRIBUTES
#df.index
#df.columns
#df.axes
#df.dtypes
#df.size
#df.shape
#df.ndim
#df.empty
#df.values


In [ ]:
#selec 1 column
print(df["name"])

In [ ]:
#selec 2 column
print(df[["name","age"]])

In [ ]:
#selec 3 column
print(df[["name","age","gender"]])#point give [ [  ] ]  form for print two,three columns values

In [ ]:
print(df.loc[:])#two row

In [ ]:
print(df.loc[1])#only one row

In [ ]:
#matplotlib library practicval 11
import matplotlib.pyplot as plt
sales=[210,270,300,350,400,300,200,600]
year=[2011,2012,2013,2014,2015,2016,2017,2018]
plt.plot(year,sales)
plt.title("sales of johnson company")
plt.xlabel("year")
plt.ylabel("sales")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
pen=[210,270,300,350,400,300,200,600]
copy=[300,320,360,400,200,120,300,350]
year=[2011,2012,2013,2014,2015,2016,2017,2018]
plt.plot(year,pen,color="yellow",label="pen",linestyle="-",linewidth=2,marker="o",markersize=5)
plt.plot(year,copy,color="blue",label="copy",linestyle=":",linewidth=4,marker="o",markersize=5)
plt.title("sales of johnson company")
plt.xlabel("year")
plt.ylabel("sales")
plt.legend()  #shows coner  points x` is and y is
plt.show()

In [ ]:
#BAR GRAPH LEARN

import matplotlib.pyplot as plt
Name=["ssuman","rakesh","sanjay","vinod","raavi","yogesh","umesh"]
marks=[33,22,11,55,77,99,55]
plt.bar(Name,marks)
plt.title("Result")
plt.xlabel("Name")
plt.ylabel("marks")
plt.legend()
plt.show()

In [ ]:
#use of x limit
import matplotlib.pyplot as plt
Name=["ssuman","rakesh","sanjay","vinod","raavi","yogesh","umesh"]
marks=[33,22,11,55,77,99,55]
plt.bar(marks,Name,color="red",width=0.9) #same like as above bar also parameters wiidth by default 0.8
plt.title("Result")
plt.ylabel("Name")
plt.xlabel("marks")
plt.xlim(11,55)   #only shows upto daat of range between 11 to 55
#plt.xlim(50,100)   #only shows those data between 50 to 100
plt.legend()
plt.show()

In [ ]:
#HISTOGRAM
import matplotlib.pyplot as plt
marks=[20,13,29,30,48,22,88,32]
#plt.hist(marks)   #noote in histogram only one axis shows
#plt.hist(marks,width=0.9,bins=[0,33,45,60,100])  #==>show 0 to 32=6, 45 to 60=1,  60 to 100=1
plt.show()

In [ ]:
study_hours = [1, 2, 3, 4, 5]
marks = [20, 40, 60, 80, 100]

# Create the plot
plt.plot(study_hours, marks, label="Marks and hours",
         linestyle='-', color='blue', marker='o')

# Add title and labels
plt.title("Study Hours vs Marks")
plt.xlabel("No. of hours")
plt.ylabel("Marks")

# Add legend
plt.legend()

# Display the plot
plt.grid(True) # adds a grid to the graph.its shows grid
plt.show()

In [ ]:
"""Develop a Python program using the Matplotlib
library to generate a line graph where the data for
both the X-axis (Study Hours) and Y-axis (Marks
Obtained) is provided by the user.The program
must:
a) Accept a single integer N, representing the
number of data points.
b) Accept N integer values for the X-axis (Study
Hours).
c) Accept N integer values for the Y-axis (Marks
Obtained).
d) Generate a line plot with the following
customizations:
● Title: "Student Performance Analysis".
● Axis Labels: X-axis as "Hours Studied" and Y-axis as
"Marks (0-100)".
● CustomizaƟon: Use a blue color, a solid line style,
and a square marker.
● Legend: "Performance Data"."""
import matplotlib.pyplot as plt
# a) Accept a single integer N (number of data points)
n = int(input("Enter the number of data points (N): "))
 # Lists to store the axis data
study_hours = []
marks_obtained = []

# b) Accept N integer values for the X-axis (Study Hours)print(f"\nEnter {n} values for Study Hours (X-axis):")
for i in range(n):
   val = int(input(f"  Value {i+1}: "))
   study_hours.append(val)

 # c) Accept N integer values for the Y-axis (Marks Obtained)
print(f"\nEnter {n} values for Marks Obtained (Y-axis):")
for i in range(n):
  val = int(input(f"  Value {i+1}: "))
  marks_obtained.append(val)

  # d) Generate the line plot with specific customizations
  # color='blue', linestyle='-' (solid), marker='s' (square)
plt.plot(study_hours, marks_obtained, color='blue',
                 linestyle='-', marker='s', label='Performance Data')
 # Set Title
plt.title("Student Performance Analysis")

# Set Axis Labels
plt.xlabel("Hours Studied")
plt.ylabel("Marks (0-100)")

 # Add Legend
plt.legend()

  # Display the plot
plt.show()